### ISSUE TITLE
[S1 - PBI1] Membuat halaman registrasi

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#1]
Sebagai Pasien, saya ingin melakukan registrasi untuk membuat dan mendapatkan akun agar bisa mengakses website.
(activity diagram, uml, tampilan, dan erd masukin ke preview)

**Comment by AbdulGhaniMuzakki** [comment]
![Image](https://user-images.githubusercontent.com/115617101/230871665-1406f058-5faf-49d9-9b0b-7d83f0cbdf1d.png)
