### ISSUE TITLE
[S2 - PBI10] Membuat halaman read event

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#10]
Sebagai Pasien, saya ingin mengakses event apabila ingin membaca event yang diinginkan.

**Comment by NasywanHanif** [comment]
Berikut merupakan halaman read event


![Image](https://user-images.githubusercontent.com/115606707/231342746-d7cb94e8-11cb-4357-ba33-84ba172452fb.png)
