### ISSUE TITLE
[S2 - PBI11] Membuat halaman input event

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#11]
Sebagai Admin, saya ingin melakukan input berbagai artikel yang bertemakan dengan stunting.

**Comment by NasywanHanif** [comment]
Berikut merupakan halaman input event


![Image](https://user-images.githubusercontent.com/115606707/231342878-8f0be626-33f1-4441-8c7e-d1d10e5b9a59.png)
