### ISSUE TITLE
[S2 - PBI12] Membuat halaman update event

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#12]
Sebagai Admin, saya ingin melakukan update artikel apabila ingin perbarui artikel tersebut.

**Comment by NasywanHanif** [comment]
Berikut halaman update event


![Image](https://user-images.githubusercontent.com/115606707/231342954-1267d50c-d7f0-49d0-a304-5601163f2568.png)
