### ISSUE TITLE
[S2 - PBI13] Membuat halaman delete event

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#13]
Sebagai Admin, saya ingin melakukan delete artikel apabila ingin menghapus artikel yang diinginkan.

**Comment by NasywanHanif** [comment]
Berikut merupakan halaman delete event


![Image](https://user-images.githubusercontent.com/115606707/231343034-49f33d40-71ae-4e34-b3ab-a8f85e3d5a36.png)
