### ISSUE TITLE
[S2 - PBI14] Membuat halaman input rekam medis ibu hamil

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#14]
Sebagai Admin, saya ingin melakukan input rekam medis ibu hamil.

**Comment by najlalya** [comment]
![Image](https://user-images.githubusercontent.com/85793898/231356719-3110cba0-9d65-4d86-8e99-dd0380c13f2c.png)
