### ISSUE TITLE
[S2 - PBI15] Membuat halaman update rekam medis ibu hamil

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#15]
Sebagai Admin, saya ingin melakukan update rekam medis ibu hamil apabila ingin perbarui hasil rekam medis ibu hamil.

**Comment by najlalya** [comment]
![Image](https://user-images.githubusercontent.com/85793898/231357424-ad56d204-c600-4cb2-a451-2981bb0841db.png)
