### ISSUE TITLE
[S2 - PBI16] Membuat halaman delete rekam medis ibu hamil

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#16]
Sebagai Admin, saya ingin melakukan delete rekam medis ibu hamil apabila ingin menghapus hasil rekam medis ibu hamil.

**Comment by najlalya** [comment]
![Image](https://user-images.githubusercontent.com/85793898/231358017-f6856333-8c65-42c6-8c1e-4b942bc7da6a.png)
