### ISSUE TITLE
[S2 - PBI17] Membuat halaman read rekam medis ibu hamil

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#17]
Sebagai Pasien, saya ingin mengakses rekam medis ibu hamil apabila ingin melihat hasil rekam medis ibu hamil.

**Comment by najlalya** [comment]
![Image](https://user-images.githubusercontent.com/85793898/231358179-79b1e575-31b3-4d4e-a401-0bacfbc67c08.png)
