### ISSUE TITLE
[S1 - PBI2] Membuat halaman login

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#2]
Sebagai Admin dan Pasien, saya ingin melakukan login untuk dapat mengakses dan menggunakan layanan pada website tersebut.
(activity diagram, uml, tampilan, dan erd masukin ke preview)

**Comment by AbdulGhaniMuzakki** [comment]
![Image](https://user-images.githubusercontent.com/115617101/230871794-7ce4f1a2-a687-4e55-aeb2-38dbc41fe07c.png)
