### ISSUE TITLE
[S1 - PBI3] Membuat halaman home

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#3]
Sebagai Admin dan Pasien, saya ingin melihat berbagai fitur dan layanan apa saja yang tersedia pada halaman utama website.
(activity diagram, uml, tampilan, dan erd masukin ke preview)

**Comment by AbdulGhaniMuzakki** [comment]
![Image](https://user-images.githubusercontent.com/115617101/230872017-a8831bab-8777-412e-a748-e1b981138410.png)
