### ISSUE TITLE
[S2 - PBI6] Membuat halaman read artikel

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#6]
Sebagai Pasien, saya ingin mengakses artikel apabila ingin membaca artikel yang diinginkan.

**Comment by NasywanHanif** [comment]
![Image](https://user-images.githubusercontent.com/115606707/231339182-6849c5c6-b64a-4a26-a9d5-4fe3d190dc48.png)
