### ISSUE TITLE
[S2 - PBI7] Membuat halaman input artikel

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#7]
Sebagai Admin, saya ingin melakukan input berbagai artikel yang bertemakan dengan stunting.

**Comment by NasywanHanif** [comment]
Berikut merupakan mockup tampilan dari input artikel


![Image](https://user-images.githubusercontent.com/115606707/231339447-0bfd7fa4-2eac-4ed8-926f-9e72ae7e8b15.png)
