### ISSUE TITLE
[S2 - PBI8] Membuat halaman update artikel

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#8]
Sebagai Admin, saya ingin melakukan update artikel apabila ingin perbarui artikel tersebut.

**Comment by NasywanHanif** [comment]
Berikut merupakan mockup tampilan halaman update artikel


![Image](https://user-images.githubusercontent.com/115606707/231339593-4cb9c1b9-205f-4da6-8ac3-a38782799321.png)
