### ISSUE TITLE
[S2 - PBI9] Membuat halaman delete artikel

### ISSUE THREAD

**Issue by nurhidayatiii** [SI-RPL-2023/SI4408_KEL267_CeSting#9]
Sebagai Admin, saya ingin melakukan delete artikel apabila ingin menghapus artikel yang diinginkan.

**Comment by NasywanHanif** [comment]
Berikut tampilan dari halaman untuk melakukan delete artikel


![Image](https://user-images.githubusercontent.com/115606707/231339762-4d12a9f7-68e7-422d-b85f-82f89da3d333.png)
